easy_admin:
    entities:
        FavouriteCity:
          class: App\Entity\FavouriteCity
          list:
                fields: ['id', 'name', 'countryCode','owm_id']
          new:
                fields:
                    - '-id'
          form:
                fields: ['id', 'name', 'countryCode', 'owm_id']
